### PR TITLE
fix: make the easy tool repair compatible with TGregworks

### LINKED ISSUE #20961: Crash to Server Selection with Tinkers Tool in 2x2 Grid
### Your GTNH Discord Username

shawnbyday

### Your Pack Version

2.8.0-Beta2

### Your Server

Private

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

With easy tool repair turned on in iguanas put tool into 2x2 grid to repair.

### The Reality

Turned on Iguanas Easy Tool repair to allow tool repair in 2x2 grid. When put tinkers tool in 2x2 grid you crash immediately to server selection screen. Many times after logging back in the tinkers tool is on the ground and duplicated.

### Your Proposal

Fix to not crash to server select screen.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by jordanamr**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20961
Crash caused by a regression in https://github.com/Vexatos/TinkersGregworks/pull/61, no ModToolRepair was available while loading the recipe, which caused an NPE.

One of my first contribution, I'd be glad to have some feedback, was unsure about the actual check but it fixes the bug for me.

### CODE REVIEW

File: src/main/java/iguanaman/iguanatweakstconstruct/tweaks/RepairCraftingRecipe.java [hunk 1]
```diff
@@ -23,18 +26,33 @@ public class RepairCraftingRecipe implements IRecipe {
...
 
-    private ModToolRepair modifier = null;
+    private ItemModifier modifier = null;
     private ItemStack modifiedTool = null;
 
     public RepairCraftingRecipe() {
-        for (ItemModifier mod : ModifyBuilder.instance.itemModifiers) if (mod instanceof ModToolRepair) {
-            modifier = (ModToolRepair) mod;
-            break;
+        boolean gregworksLoaded = Loader.isModLoaded("TGregworks");
```
Comment (mitchej123) [inline src/main/java/iguanaman/iguanatweakstconstruct/tweaks/RepairCraftingRecipe.java]: NIT: 
1) Do this at the mod container level, once.  It might only be created once here, but this avoids people thinking this is a universal pattern.
2) Do it this way, document why it's ok in this case and not the general case so people don't copy it

File: src/main/java/iguanaman/iguanatweakstconstruct/tweaks/RepairCraftingRecipe.java [hunk 2]
```diff
@@ -23,18 +26,33 @@ public class RepairCraftingRecipe implements IRecipe {
...
+        for (ItemModifier mod : ModifyBuilder.instance.itemModifiers) {
+            // If TGregworks is present, use ModTGregRepair instead of ModToolRepair
+            if (gregworksLoaded && isTGregRepairModifier(mod)) {
```
Comment (mitchej123) [inline src/main/java/iguanaman/iguanatweakstconstruct/tweaks/RepairCraftingRecipe.java]: I forget the specific details of how/when class loading works -- seems fine if this works w/o tgregworks loaded, but please validate.  Seems fine since the instanceof check is in another method...

Comment (jordanamr) [reply src/main/java/iguanaman/iguanatweakstconstruct/tweaks/RepairCraftingRecipe.java]: I'll double check tomorrow on a barebone forge install

File: src/main/java/iguanaman/iguanatweakstconstruct/tweaks/RepairCraftingRecipe.java (hunk 1 above)
Comment (jordanamr) [reply src/main/java/iguanaman/iguanatweakstconstruct/tweaks/RepairCraftingRecipe.java]: I realized that this mod has a ModSupportHelper class with static instances of mod checks. Switched to this.

File: src/main/java/iguanaman/iguanatweakstconstruct/tweaks/RepairCraftingRecipe.java (hunk 2 above)
Comment (jordanamr) [reply src/main/java/iguanaman/iguanatweakstconstruct/tweaks/RepairCraftingRecipe.java]: Tested on a barebone forge install with only these mods loaded:
image

Easy tool repair still works as expected.
Also tested on 2.8.0-beta4, repair works as expected too with TGregworks loaded

**Review by wlhlm — APPROVED** [review]
Thank you!
